tmux:
  tmux new -ds synth-pi -n "README"
  tmux send-keys -t synth-pi:README 'nv ./README.md "+set wrap"' ENTER
  @just new-window "Reff" ""
  @just new-window "Edit" ""
  @just new-window "Run" ""
  @just new-window "git" "git status"
  tmux a -t synth-pi

new-window NAME CMD:
  tmux new-w -t synth-pi -n "{{NAME}}"
  tmux send-keys -t synth-pi:"{{NAME}}" "{{CMD}}" ENTER

