run:
  WEBKIT_DISABLE_COMPOSITING_MODE=1 cargo +nightly tauri dev -f "HiFi" --release

dev:
  WEBKIT_DISABLE_COMPOSITING_MODE=1 cargo +nightly tauri dev

release:
  WEBKIT_DISABLE_COMPOSITING_MODE=1 cargo +nightly tauri dev --release

build:
  # cargo tauri build -f "HiFi"
  WEBKIT_DISABLE_COMPOSITING_MODE=1 cargo +nightly tauri build -f "HiFi"

tailwind:
  npm list @catppuccin/tailwindcss > /dev/null || npm install -D @catppuccin/tailwindcss
  npx tailwindcss -i ./input.css -o ./styles.css --watch

new-window NAME CMD:
  tmux new-w -t desk-8080 -n "{{NAME}}"
  tmux send-keys -t desk-8080:"{{NAME}}" "{{CMD}}" ENTER

tmux:
  tmux new -ds desk-8080 -n "README"
  tmux send-keys -t desk-8080:README 'nv ./README.md "+set wrap"' ENTER
  @just new-window "Edit" ""
  @just new-window "Run" ""
  @just new-window "git" "git status"
  tmux a -t desk-8080
