run:
  cargo tauri dev -f "HiFi" --release

dev:
  cargo tauri dev

release:
  cargo tauri dev --release

build:
  cargo tauri build -f "HiFi"

tailwind:
  npm list @catppuccin/tailwindcss > /dev/null || npm install -D @catppuccin/tailwindcss
  npx tailwindcss -i ./input.css -o ./styles.css --watch
